### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by AMufInABox** [FenrirBots/BO3RPC#2]
Hey there! Will this project still be updated?

**Comment by FenrirBots** [comment]
Hey there! I was intending to update it awhile ago but I started having issues with black ops 3 causing me to stop working on it.
If I get around to it in the near future I will Definately have a look at updating it.

**Comment by FenrirBots** [comment]
Hi again. I am currently updating it right now with a bit of a rewrite. I also managed to finish the launcher for it so it should do its own thing without the use of anything external like processhacker.
